export const data = [
  {
    received_from: "massa donec",
    receipt_no: 1,
    "cash/bank": false,
    total_amount: 63,
    rmi: 80,
    other_votheads: 54,
    date: "03/23/2024",
    account: "eget",
  },
  {
    received_from: "sem",
    receipt_no: 2,
    "cash/bank": true,
    total_amount: 33,
    rmi: 26,
    other_votheads: 83,
    date: "03/27/2024",
    account: "volutpat",
  },
  {
    received_from: "morbi non",
    receipt_no: 3,
    "cash/bank": false,
    total_amount: 17,
    rmi: 19,
    other_votheads: 95,
    date: "07/30/2024",
    account: "aliquet",
  },
  {
    received_from: "donec quis",
    receipt_no: 4,
    "cash/bank": true,
    total_amount: 94,
    rmi: 17,
    other_votheads: 90,
    date: "04/11/2024",
    account: "libero",
  },
  {
    received_from: "orci",
    receipt_no: 5,
    "cash/bank": false,
    total_amount: 64,
    rmi: 68,
    other_votheads: 84,
    date: "04/08/2024",
    account: "ipsum",
  },
  {
    received_from: "vestibulum eget",
    receipt_no: 6,
    "cash/bank": true,
    total_amount: 66,
    rmi: 24,
    other_votheads: 67,
    date: "05/22/2024",
    account: "ac",
  },
  {
    received_from: "nisi vulputate nonummy",
    receipt_no: 7,
    "cash/bank": true,
    total_amount: 68,
    rmi: 47,
    other_votheads: 79,
    date: "09/18/2023",
    account: "ut",
  },
  {
    received_from: "eu felis fusce",
    receipt_no: 8,
    "cash/bank": true,
    total_amount: 75,
    rmi: 50,
    other_votheads: 71,
    date: "09/01/2023",
    account: "et",
  },
  {
    received_from: "quis libero",
    receipt_no: 9,
    "cash/bank": false,
    total_amount: 1,
    rmi: 79,
    other_votheads: 7,
    date: "08/14/2023",
    account: "aliquet",
  },
  {
    received_from: "sed",
    receipt_no: 10,
    "cash/bank": false,
    total_amount: 88,
    rmi: 9,
    other_votheads: 44,
    date: "03/05/2024",
    account: "scelerisque",
  },
  {
    received_from: "nunc purus phasellus",
    receipt_no: 11,
    "cash/bank": false,
    total_amount: 70,
    rmi: 25,
    other_votheads: 30,
    date: "09/16/2023",
    account: "condimentum",
  },
  {
    received_from: "aliquet maecenas leo",
    receipt_no: 12,
    "cash/bank": false,
    total_amount: 56,
    rmi: 7,
    other_votheads: 90,
    date: "12/09/2023",
    account: "lacinia",
  },
  {
    received_from: "ut mauris",
    receipt_no: 13,
    "cash/bank": false,
    total_amount: 18,
    rmi: 4,
    other_votheads: 56,
    date: "01/29/2024",
    account: "turpis",
  },
  {
    received_from: "at nulla suspendisse",
    receipt_no: 14,
    "cash/bank": true,
    total_amount: 95,
    rmi: 37,
    other_votheads: 51,
    date: "03/12/2024",
    account: "donec",
  },
  {
    received_from: "ultrices",
    receipt_no: 15,
    "cash/bank": true,
    total_amount: 15,
    rmi: 51,
    other_votheads: 16,
    date: "01/16/2024",
    account: "quis",
  },
  {
    received_from: "magna vestibulum aliquet",
    receipt_no: 16,
    "cash/bank": false,
    total_amount: 47,
    rmi: 85,
    other_votheads: 79,
    date: "11/08/2023",
    account: "ac",
  },
  {
    received_from: "et eros vestibulum",
    receipt_no: 17,
    "cash/bank": false,
    total_amount: 13,
    rmi: 50,
    other_votheads: 68,
    date: "09/07/2023",
    account: "vivamus",
  },
  {
    received_from: "congue vivamus metus",
    receipt_no: 18,
    "cash/bank": true,
    total_amount: 98,
    rmi: 54,
    other_votheads: 68,
    date: "08/12/2023",
    account: "dolor",
  },
  {
    received_from: "dolor morbi",
    receipt_no: 19,
    "cash/bank": false,
    total_amount: 67,
    rmi: 43,
    other_votheads: 67,
    date: "12/18/2023",
    account: "in",
  },
  {
    received_from: "a pede posuere",
    receipt_no: 20,
    "cash/bank": true,
    total_amount: 32,
    rmi: 17,
    other_votheads: 87,
    date: "01/14/2024",
    account: "posuere",
  },
  {
    received_from: "eu felis fusce",
    receipt_no: 21,
    "cash/bank": false,
    total_amount: 1,
    rmi: 73,
    other_votheads: 44,
    date: "04/20/2024",
    account: "nulla",
  },
  {
    received_from: "id pretium",
    receipt_no: 22,
    "cash/bank": false,
    total_amount: 42,
    rmi: 17,
    other_votheads: 41,
    date: "02/15/2024",
    account: "faucibus",
  },
  {
    received_from: "sodales scelerisque",
    receipt_no: 23,
    "cash/bank": false,
    total_amount: 14,
    rmi: 35,
    other_votheads: 76,
    date: "03/28/2024",
    account: "odio",
  },
  {
    received_from: "est",
    receipt_no: 24,
    "cash/bank": false,
    total_amount: 31,
    rmi: 65,
    other_votheads: 14,
    date: "03/08/2024",
    account: "ipsum",
  },
  {
    received_from: "odio donec vitae",
    receipt_no: 25,
    "cash/bank": true,
    total_amount: 36,
    rmi: 46,
    other_votheads: 43,
    date: "05/14/2024",
    account: "consectetuer",
  },
  {
    received_from: "aliquet maecenas",
    receipt_no: 26,
    "cash/bank": true,
    total_amount: 71,
    rmi: 35,
    other_votheads: 97,
    date: "04/25/2024",
    account: "tincidunt",
  },
  {
    received_from: "aliquam",
    receipt_no: 27,
    "cash/bank": true,
    total_amount: 70,
    rmi: 83,
    other_votheads: 97,
    date: "10/19/2023",
    account: "tristique",
  },
  {
    received_from: "tortor",
    receipt_no: 28,
    "cash/bank": false,
    total_amount: 26,
    rmi: 26,
    other_votheads: 78,
    date: "05/06/2024",
    account: "varius",
  },
  {
    received_from: "et",
    receipt_no: 29,
    "cash/bank": false,
    total_amount: 62,
    rmi: 76,
    other_votheads: 31,
    date: "12/25/2023",
    account: "tristique",
  },
  {
    received_from: "quam",
    receipt_no: 30,
    "cash/bank": true,
    total_amount: 17,
    rmi: 11,
    other_votheads: 100,
    date: "06/03/2024",
    account: "odio",
  },
  {
    received_from: "leo",
    receipt_no: 31,
    "cash/bank": false,
    total_amount: 20,
    rmi: 87,
    other_votheads: 75,
    date: "12/10/2023",
    account: "nisi",
  },
  {
    received_from: "sapien",
    receipt_no: 32,
    "cash/bank": false,
    total_amount: 6,
    rmi: 79,
    other_votheads: 19,
    date: "05/02/2024",
    account: "eget",
  },
  {
    received_from: "id ligula suspendisse",
    receipt_no: 33,
    "cash/bank": true,
    total_amount: 95,
    rmi: 32,
    other_votheads: 43,
    date: "01/27/2024",
    account: "tellus",
  },
  {
    received_from: "ipsum",
    receipt_no: 34,
    "cash/bank": true,
    total_amount: 62,
    rmi: 24,
    other_votheads: 52,
    date: "11/16/2023",
    account: "diam",
  },
  {
    received_from: "eleifend luctus",
    receipt_no: 35,
    "cash/bank": false,
    total_amount: 29,
    rmi: 34,
    other_votheads: 15,
    date: "07/04/2024",
    account: "tortor",
  },
  {
    received_from: "in lacus",
    receipt_no: 36,
    "cash/bank": true,
    total_amount: 67,
    rmi: 25,
    other_votheads: 42,
    date: "05/11/2024",
    account: "nam",
  },
  {
    received_from: "quis tortor",
    receipt_no: 37,
    "cash/bank": true,
    total_amount: 89,
    rmi: 56,
    other_votheads: 36,
    date: "06/03/2024",
    account: "sapien",
  },
  {
    received_from: "penatibus et",
    receipt_no: 38,
    "cash/bank": true,
    total_amount: 52,
    rmi: 47,
    other_votheads: 3,
    date: "04/08/2024",
    account: "adipiscing",
  },
  {
    received_from: "donec",
    receipt_no: 39,
    "cash/bank": true,
    total_amount: 73,
    rmi: 13,
    other_votheads: 24,
    date: "09/16/2023",
    account: "nec",
  },
  {
    received_from: "sit amet",
    receipt_no: 40,
    "cash/bank": true,
    total_amount: 21,
    rmi: 47,
    other_votheads: 83,
    date: "03/02/2024",
    account: "a",
  },
  {
    received_from: "consectetuer",
    receipt_no: 41,
    "cash/bank": true,
    total_amount: 16,
    rmi: 45,
    other_votheads: 57,
    date: "03/08/2024",
    account: "integer",
  },
  {
    received_from: "mauris",
    receipt_no: 42,
    "cash/bank": false,
    total_amount: 2,
    rmi: 26,
    other_votheads: 38,
    date: "01/30/2024",
    account: "nisl",
  },
  {
    received_from: "leo odio porttitor",
    receipt_no: 43,
    "cash/bank": true,
    total_amount: 44,
    rmi: 71,
    other_votheads: 40,
    date: "11/16/2023",
    account: "justo",
  },
  {
    received_from: "tellus",
    receipt_no: 44,
    "cash/bank": true,
    total_amount: 48,
    rmi: 15,
    other_votheads: 46,
    date: "03/22/2024",
    account: "eu",
  },
  {
    received_from: "tellus semper",
    receipt_no: 45,
    "cash/bank": false,
    total_amount: 53,
    rmi: 8,
    other_votheads: 69,
    date: "07/05/2024",
    account: "interdum",
  },
  {
    received_from: "sapien urna",
    receipt_no: 46,
    "cash/bank": true,
    total_amount: 51,
    rmi: 97,
    other_votheads: 67,
    date: "06/29/2024",
    account: "eget",
  },
  {
    received_from: "sit amet lobortis",
    receipt_no: 47,
    "cash/bank": false,
    total_amount: 64,
    rmi: 3,
    other_votheads: 30,
    date: "10/09/2023",
    account: "orci",
  },
  {
    received_from: "volutpat",
    receipt_no: 48,
    "cash/bank": true,
    total_amount: 64,
    rmi: 37,
    other_votheads: 48,
    date: "03/31/2024",
    account: "neque",
  },
  {
    received_from: "sapien",
    receipt_no: 49,
    "cash/bank": true,
    total_amount: 27,
    rmi: 75,
    other_votheads: 41,
    date: "12/31/2023",
    account: "vestibulum",
  },
  {
    received_from: "molestie hendrerit at",
    receipt_no: 50,
    "cash/bank": true,
    total_amount: 82,
    rmi: 80,
    other_votheads: 58,
    date: "09/09/2023",
    account: "justo",
  },
];
